from reportlab.platypus import (
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib.units import inch
from reportlab.lib import colors

from schemas.itinerary import Itinerary
from utils.pdfs.styles import *


def build_cover(story, itinerary: Itinerary):

    trip = itinerary.trip_summary

    # ======================================================
    # TITLE
    # ======================================================

    story.append(
        Paragraph(
            "✈ VOYAGE AI",
            TITLE
        )
    )

    story.append(
        Paragraph(
            "AI Powered Travel Planner",
            SUBTITLE
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # ======================================================
    # DESTINATION
    # ======================================================

    story.append(
        Paragraph(
            trip.destination.upper(),
            TITLE
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    # ======================================================
    # SUMMARY CARD
    # ======================================================

    cover_table = Table(
        [

            ["📍 Destination", trip.destination],

            ["🛫 Departure", trip.departure_city],

            [
                "📅 Travel Dates",
                f"{trip.departure_date} → {trip.return_date}"
            ],

            ["👥 Travelers", str(trip.travelers)],

            [
                "💰 Budget",
                f"{trip.currency}{trip.budget:,.0f}"
            ],

        ],
        colWidths=[170,250]
    )

    cover_table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(0,-1),LIGHT_BLUE),

            ("BACKGROUND",(1,0),(1,-1),colors.white),

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),10),

            ("TOPPADDING",(0,0),(-1,-1),10),

            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),

            ("VALIGN",(0,0),(-1,-1),"MIDDLE"),

        ])

    )

    story.append(cover_table)

    story.append(Spacer(1, 0.4 * inch))

    # ======================================================
    # QUOTE
    # ======================================================

    story.append(
        Paragraph(
            "<i>"
            "\"Travel is the only thing you buy that makes you richer.\""
            "</i>",
            BODY
        )
    )

    story.append(Spacer(1, 0.5 * inch))

    # ======================================================
    # GENERATED DATE
    # ======================================================

    story.append(
        Paragraph(
            "Generated by Voyage AI",
            SMALL
        )
    )

    story.append(
        Paragraph(
            "AI Powered Personalized Travel Planning",
            SMALL
        )
    )

    # ======================================================
    # NEW PAGE
    # ======================================================

    story.append(PageBreak())