from reportlab.platypus import (
    Table,
    TableStyle,
    Paragraph,
    Spacer
)

from reportlab.lib import colors
from reportlab.lib.units import inch

from utils.pdfs.styles import *


# ==========================================================
# SECTION SPACER
# ==========================================================

def add_space(story, height=0.2):
    """
    Adds vertical space between sections.
    height is in inches.
    """
    story.append(Spacer(1, height * inch))


# ==========================================================
# SECTION TITLE
# ==========================================================

def add_section_title(story, title):

    story.append(
        Paragraph(
            title,
            SECTION
        )
    )


# ==========================================================
# STANDARD TABLE
# ==========================================================

def create_table(data,
                 col_widths,
                 header_color=LIGHT_BLUE):

    table = Table(
        data,
        colWidths=col_widths
    )

    table.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),

            ("BACKGROUND",(0,0),(0,-1),header_color),

            ("BACKGROUND",(1,0),(1,-1),colors.white),

            ("BOTTOMPADDING",(0,0),(-1,-1),10),

            ("TOPPADDING",(0,0),(-1,-1),10),

            ("VALIGN",(0,0),(-1,-1),"TOP"),

            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),

        ])

    )

    return table


# ==========================================================
# BUDGET TABLE
# ==========================================================

def create_budget_table(data):

    table = Table(
        data,
        colWidths=[220,180]
    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),WHITE),

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),10),

            ("TOPPADDING",(0,0),(-1,-1),10),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("FONTNAME",(0,-2),(-1,-1),"Helvetica-Bold"),

        ])

    )

    return table


# ==========================================================
# BULLET LIST
# ==========================================================

def add_bullet_list(story, items):

    for item in items:

        story.append(

            Paragraph(

                f"• {item}",

                BODY

            )

        )


# ==========================================================
# MONEY SAVING LIST
# ==========================================================

def add_saving_tips(story, tips):

    for tip in tips:

        story.append(

            Paragraph(

                f"• <b>{tip.tip}</b><br/>"

                f"<font color='green'>"

                f"Estimated Saving: ₹{tip.estimated_saving:,.0f}"

                f"</font>",

                BODY

            )

        )

        story.append(
            Spacer(1,8)
        )


# ==========================================================
# HORIZONTAL DIVIDER
# ==========================================================

def divider():

    table = Table(
        [[""]],
        colWidths=[470]
    )

    table.setStyle(

        TableStyle([

            ("LINEBELOW",(0,0),(-1,-1),1,PRIMARY),

        ])

    )

    return table


# ==========================================================
# FOOTER
# ==========================================================

def footer():

    return Paragraph(

        "<br/><br/>"

        "<b>Generated by Voyage AI</b><br/>"

        "AI Powered Travel Planner",

        FOOTER

    )